name: DQNAgent
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - stable-baselines3
  - gym
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - transformers

